name: Vint Tests

on:
  pull_request:

jobs:
  test-vint:
    runs-on: ubuntu-latest
    container:
      image: verilator/verilator:v5.050

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install test dependencies
        run: |
            verilator --version
            apt-get update
            apt-get install -y build-essential cmake ninja-build libgtest-dev libboost-dev liblz4-dev

      - name: Configure CMake
        run: cmake -S . -B build -G Ninja

      - name: Build CI targets
        run: cmake --build build --target sim_validready_cpptop sim_validready_cppsplit sim_validready_testbench test_vint test_shim

      - name: Run sim_validready_cpptop
        run: ./build/sim/validready/sim_validready_cpptop

      - name: Run sim_validready_cppsplit
        run: ./build/sim/validready/sim_validready_cppsplit

      - name: Run sim_validready_testbench
        run: ./build/sim/validready/sim_validready_testbench

      - name: Run vint tests
        run: ctest --test-dir build --output-on-failure -R VintTests

      - name: Run shim tests
        run: ctest --test-dir build --output-on-failure -R ShimTests
